export const CHECK_ITEMS = [
  "satisfactory_starting",
  "battery_voltage",
  "ac_heating_demist",
  "audio_radio_cd_aux_bluetooth",
  "bluetooth_media",
  "dab",
  "infotainment_sat_nav",
  "android_auto_apple_carplay",
  "owners_guide",
  "sun_visor_glass",
  "seat_heated",
  "seat_ventilated",
  "seats_electric",
  "seats_manual",
  "seats_memory",
  "car_mats",
  "external_mirrors",
  "power_folding_mirrors",
  "rear_view_mirror",
  "exterior_lights",
  "wipers_washers",
  "steering_wheel_adjustment",
  "convertible_roof",
  "sunroof_blind",
  "hazard_lights",
  "interior_lights",
  "stop_start",
  "air_suspension",
  "handbrake",
  "park_assist",
  "rear_parking_sensors",
  "front_rear_parking_sensors",
  "reverse_camera",
  "cameras_360",
  "sockets_12v_usb",
  "air_vents",
  "windows",
  "bonnet_release",
  "door_locks",
  "seatbelt_operation",
  "fuel_flap_filler_cap",
  "power_tailgate",
  "parcel_shelf",
  "spare_tyre",
  "liquid_kit_compressor",
  "locking_wheel_nut",
  "toolkit",
  "water_ingress",
  "discs_pads_condition",
  "diagnostic_checks",
] as const;

export type CheckItemKey = (typeof CHECK_ITEMS)[number];

export const CHECK_ITEM_LABELS: Record<CheckItemKey, string> = {
  satisfactory_starting: "Satisfactory Starting, General Performance",
  battery_voltage: "Battery Voltage",
  ac_heating_demist: "A/C, Heating & Demist Systems",
  audio_radio_cd_aux_bluetooth: "Audio, Radio, CD, Aux, Bluetooth",
  bluetooth_media: "Bluetooth Media",
  dab: "DAB",
  infotainment_sat_nav: "Infotainment - Sat Nav",
  android_auto_apple_carplay: "Android Auto / Apple CarPlay",
  owners_guide: "Physical or Digital Owners Guide",
  sun_visor_glass: "Sun Visor & Glass",
  seat_heated: "Seat Operation - Heated",
  seat_ventilated: "Seat Operation - Ventilated",
  seats_electric: "Seats - Electric Movement",
  seats_manual: "Seats - Manual Movement",
  seats_memory: "Seats - Memory Function",
  car_mats: "Car Mats",
  external_mirrors: "External Mirrors",
  power_folding_mirrors: "Power Folding Mirrors",
  rear_view_mirror: "Rear View Mirror",
  exterior_lights: "Exterior Light Equipment",
  wipers_washers: "Wipers & Washers",
  steering_wheel_adjustment: "Steering Wheel Adjustment",
  convertible_roof: "Convertible Roof (if applicable)",
  sunroof_blind: "Sunroof & Blind",
  hazard_lights: "Hazard Lights",
  interior_lights: "Interior Lights",
  stop_start: "Stop/Start (if applicable)",
  air_suspension: "Air Suspension (if applicable)",
  handbrake: "Handbrake",
  park_assist: "Park Assist Systems",
  rear_parking_sensors: "Rear Parking Sensors",
  front_rear_parking_sensors: "Front & Rear Parking Sensors",
  reverse_camera: "Reverse Camera",
  cameras_360: "360 Cameras",
  sockets_12v_usb: "12V Sockets / USB Ports",
  air_vents: "Air Vents Intact",
  windows: "Windows",
  bonnet_release: "Bonnet Release",
  door_locks: "Door Locks",
  seatbelt_operation: "Seatbelt Operation",
  fuel_flap_filler_cap: "Fuel Flap / Filler Cap",
  power_tailgate: "Power Tailgate",
  parcel_shelf: "Parcel Shelf Present / Operational",
  spare_tyre: "Spare Tyre",
  liquid_kit_compressor: "Liquid Kit & Compressor",
  locking_wheel_nut: "Locking Wheel Nut Present / Location",
  toolkit: "Toolkit",
  water_ingress: "Check for Water Ingress",
  discs_pads_condition: "Discs & Pads Condition",
  diagnostic_checks: "Diagnostic Checks Completed",
};
